/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanmedium.tugaspbo;

/**
 *
 * @author Bima4
 */
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import latihanmedium.tugaspbo.PerpusService;

public class PBOGUI extends javax.swing.JFrame {

    /**
     * Creates new form PBOGUI
     */ 
    DefaultListModel<String> dlm;
    List<Buku> items;
    PerpusService perpusService;

    
    public PBOGUI() {
        initComponents();
        
        perpusService = new PerpusService(); // Inisialisasi PerpusService
        this.items = perpusService.getAll(); // Panggil fungsi getAll dari PerpusService
        this.dlm = new DefaultListModel<>();
        this.jListHasilCariBuku.setModel(dlm);
        
        for (Buku item : items) {
            dlm.addElement(item.getJudul());
        }
    }
    
    private void tampilkanHasilPencarian(List<Buku> hasilPencarian) {
        dlm.clear();

        if (hasilPencarian.isEmpty()) {
            dlm.addElement("Tidak ada Hasil Ditemukan");
        } 
        else {
            for (Buku buku : hasilPencarian) {
                dlm.addElement(buku.getJudul());
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonIsiKehadiranMainMenu = new javax.swing.JButton();
        jButtonPinjamBukuMainMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelAbsensi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDaftarAbsensi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNamaAbsensi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButtonSubmitNama = new javax.swing.JButton();
        jPanelCariBuku = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaJudulBukuCariBuku = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaPenulisCariBuku = new javax.swing.JTextArea();
        jScrollPaneTahunTerbitCariBuku = new javax.swing.JScrollPane();
        jTextAreaTahunTerbitCariBuku = new javax.swing.JTextArea();
        jButtonCariBuku = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListHasilCariBuku = new javax.swing.JList<>();
        jButtonBukuPinjam = new javax.swing.JButton();
        jLabelKeteranganBuku = new javax.swing.JLabel();
        jButtonKembalikanBuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Selamat Datang Di Perpustakaan Sejahtera");

        jButtonIsiKehadiranMainMenu.setText("Isi Kehadiran");
        jButtonIsiKehadiranMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIsiKehadiranMainMenuActionPerformed(evt);
            }
        });

        jButtonPinjamBukuMainMenu.setText("Cari / Pinjam Buku");
        jButtonPinjamBukuMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPinjamBukuMainMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bahkan prenjak alang-alang pun suka baca buku");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPinjamBukuMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIsiKehadiranMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jButtonIsiKehadiranMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPinjamBukuMainMenu)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Main MENU ", jPanelMain);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Daftar prenjak alang alang yang mampir");

        jTableDaftarAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Pukul"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDaftarAbsensi);

        jTextAreaNamaAbsensi.setColumns(20);
        jTextAreaNamaAbsensi.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNamaAbsensi);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Isikan nama untuk mengisi kehadiran");

        jButtonSubmitNama.setText("Submit");
        jButtonSubmitNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAbsensiLayout = new javax.swing.GroupLayout(jPanelAbsensi);
        jPanelAbsensi.setLayout(jPanelAbsensiLayout);
        jPanelAbsensiLayout.setHorizontalGroup(
            jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))
                    .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButtonSubmitNama)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAbsensiLayout.setVerticalGroup(
            jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAbsensiLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanelAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButtonSubmitNama))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Absensi", jPanelAbsensi);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel6.setText("Judul Buku");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel7.setText("Penulis");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel8.setText("Tahun Terbit");

        jTextAreaJudulBukuCariBuku.setColumns(20);
        jTextAreaJudulBukuCariBuku.setRows(5);
        jScrollPane3.setViewportView(jTextAreaJudulBukuCariBuku);

        jTextAreaPenulisCariBuku.setColumns(20);
        jTextAreaPenulisCariBuku.setRows(5);
        jScrollPane4.setViewportView(jTextAreaPenulisCariBuku);

        jTextAreaTahunTerbitCariBuku.setColumns(20);
        jTextAreaTahunTerbitCariBuku.setRows(5);
        jScrollPaneTahunTerbitCariBuku.setViewportView(jTextAreaTahunTerbitCariBuku);

        jButtonCariBuku.setText("Cari Buku");
        jButtonCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariBukuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Masukkan Informasi Buku");

        jListHasilCariBuku.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jListHasilCariBuku);

        jButtonBukuPinjam.setText("Pinjam Buku");
        jButtonBukuPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBukuPinjamActionPerformed(evt);
            }
        });

        jLabelKeteranganBuku.setText("\"\"");

        jButtonKembalikanBuku.setText("Kembalikan Buku");
        jButtonKembalikanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembalikanBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCariBukuLayout = new javax.swing.GroupLayout(jPanelCariBuku);
        jPanelCariBuku.setLayout(jPanelCariBukuLayout);
        jPanelCariBukuLayout.setHorizontalGroup(
            jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                        .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonKembalikanBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonBukuPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCariBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jScrollPaneTahunTerbitCariBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabelKeteranganBuku)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanelCariBukuLayout.setVerticalGroup(
            jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                        .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCariBukuLayout.createSequentialGroup()
                                .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTahunTerbitCariBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCariBuku))
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(jPanelCariBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBukuPinjam)
                    .addComponent(jLabelKeteranganBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKembalikanBuku)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Cari Buku", jPanelCariBuku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBukuPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBukuPinjamActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListHasilCariBuku.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedJudul = dlm.getElementAt(selectedIndex);
            Buku selectedBuku = null;

            // Cari objek Buku berdasarkan judul yang dipilih
            for (Buku buku : items) {
                if (buku.getJudul().equals(selectedJudul)) {
                    selectedBuku = buku;
                    break;
                }
            }

            if (selectedBuku != null && selectedBuku.getStok() > 0) {
                // Panggil fungsi updatePinjamBuku
                perpusService.updatePinjamBuku(selectedBuku);

                // Konfirmasi peminjaman
                jLabelKeteranganBuku.setText("Buku berhasil dipinjam!");
            } else {
                // Tampilkan pesan stok habis
                jLabelKeteranganBuku.setText("Stok buku habis!");
            }
        } else {
            // Tampilkan pesan jika tidak ada buku yang dipilih
            jLabelKeteranganBuku.setText("Silakan pilih buku yang ingin dipinjam!");
        }
    }//GEN-LAST:event_jButtonBukuPinjamActionPerformed

    private void jButtonCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariBukuActionPerformed
        // Ambil inputan dari pengguna
        String judulInput = jTextAreaJudulBukuCariBuku.getText().trim();
        String penulisInput = jTextAreaPenulisCariBuku.getText().trim();
        String tahunTerbitInput = jTextAreaTahunTerbitCariBuku.getText().trim();

        // Panggil metode cariBuku dari PerpusService
        List<Buku> hasilPencarian = perpusService.cariBuku(judulInput, penulisInput, tahunTerbitInput);

        // Tampilkan hasil pencarian
        tampilkanHasilPencarian(hasilPencarian);

        // Set label keterangan berdasarkan hasil pencarian
        if (!hasilPencarian.isEmpty()) {
            jLabelKeteranganBuku.setText("Buku Ketemu");
        } else {
            jLabelKeteranganBuku.setText("Buku tidak Ditemukan");
        }
    }//GEN-LAST:event_jButtonCariBukuActionPerformed

    private void jButtonSubmitNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitNamaActionPerformed
        // TODO add your handling code here:
        String namaInput = jTextAreaNamaAbsensi.getText();
        Date sekarang = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String waktuSekarang = sdf.format(sekarang);

        DefaultTableModel model = (DefaultTableModel) jTableDaftarAbsensi.getModel();
        model.addRow(new Object[]{namaInput, waktuSekarang});
    }//GEN-LAST:event_jButtonSubmitNamaActionPerformed

    private void jButtonPinjamBukuMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinjamBukuMainMenuActionPerformed
        jTabbedPane3.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonPinjamBukuMainMenuActionPerformed

    private void jButtonIsiKehadiranMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIsiKehadiranMainMenuActionPerformed
        jTabbedPane3.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonIsiKehadiranMainMenuActionPerformed

    private void jButtonKembalikanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembalikanBukuActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedIndex = jListHasilCariBuku.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedJudul = dlm.getElementAt(selectedIndex);
            Buku selectedBuku = null;

            // Cari objek Buku berdasarkan judul yang dipilih
            for (Buku buku : items) {
                if (buku.getJudul().equals(selectedJudul)) {
                    selectedBuku = buku;
                    break;
                }
            }

            if (selectedBuku != null && selectedBuku.getBukuDipinjam() > 0) {
                // Panggil fungsi updateKembalikanBuku
                perpusService.updateKembalikanBuku(selectedBuku);

                // Konfirmasi pengembalian
                jLabelKeteranganBuku.setText("Buku berhasil dikembalikan!");
            } else {
                // Tampilkan pesan jika tidak ada buku yang dipinjam
                jLabelKeteranganBuku.setText("Tidak ada buku yang sedang dipinjam!");
            }
        } else {
            // Tampilkan pesan jika tidak ada buku yang dipilih
            jLabelKeteranganBuku.setText("Silakan pilih buku yang ingin dikembalikan!");
        }
    }//GEN-LAST:event_jButtonKembalikanBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PBOGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBukuPinjam;
    private javax.swing.JButton jButtonCariBuku;
    private javax.swing.JButton jButtonIsiKehadiranMainMenu;
    private javax.swing.JButton jButtonKembalikanBuku;
    private javax.swing.JButton jButtonPinjamBukuMainMenu;
    private javax.swing.JButton jButtonSubmitNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKeteranganBuku;
    private javax.swing.JList<String> jListHasilCariBuku;
    private javax.swing.JPanel jPanelAbsensi;
    private javax.swing.JPanel jPanelCariBuku;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneTahunTerbitCariBuku;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableDaftarAbsensi;
    private javax.swing.JTextArea jTextAreaJudulBukuCariBuku;
    private javax.swing.JTextArea jTextAreaNamaAbsensi;
    private javax.swing.JTextArea jTextAreaPenulisCariBuku;
    private javax.swing.JTextArea jTextAreaTahunTerbitCariBuku;
    // End of variables declaration//GEN-END:variables
}
